require 'dm-core'
require 'dm-validations'
require 'dm-transactions'

require 'app/models/author'
require 'app/models/collaboration'
require 'app/models/fork'
require 'app/models/project'
require 'app/models/predecession'
require 'app/models/github'
